import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import "./globals.css";
import Nav from "./components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Anaconda Clearance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" data-theme="winter">
        <head></head>
        <body className={`flex min-h-screen flex-col ${inter.className}`}>
          <Nav />
          <main className="flex-grow overflow-y-auto sticky top-0 z-50">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
